### ISSUE TITLE
"source" is NOT "import"

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#21]
Important: all `source` commands in a function *must stay within that function*. This is because `source` is not a sort of "import".

**Comment by pglpm** [comment]
@choisant Found the catch: `source([file], local=TRUE)`

**Comment by choisant** [comment]
Philosophical thoughts on the topic of where in the file/function to place source():

What do we wish to gain? Reduce the number of times source() is called unnecessarily? Make the code easier to understand? Developers/users expect dependencies to be easy to see at the top of the document. Having code which relies on you placing source() at a specific linear point in the code might mean that the code is poorly written (overlapping function/variable names?). If however, a function is called seldom, or just in some cases, a small amount of computational speed might be gained from placing source() inside that function. But if a function is called many times, then we are source()-ing more than we have to, which will probably increase computational time.

**Comment by pglpm** [comment]
The problem will be solved by defining in the main workspace all functions used by several other functions. So no `source()` will be necessary.

`source()` may be used, though, to relegate to a separate file a particular group of lines – for example lines that assign parameter values, or lines that define a function used only in the present file. This is done just for ease of editing, those lines could just be left in the original file.
In this use case, to me it makes sense to leave `source()` exactly in the place where it is called, because it isn't really a "dependency".
