### ISSUE TITLE
Construct file & directory paths using `file.path()`

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#22]
In order to combine parts of paths, the code currently uses a simple `paste0()`. Use `file.path()` instead, which creates OS-independent paths.

https://rdrr.io/r/base/file.path.html

**Comment by pglpm** [comment]
Done this in inferpopulation()

**Comment by choisant** [comment]
But not in the other functions. Let's do it globally!


- [ ] buildmetadata
- [ ] util_buildauxmetadata.R
- [ ] [util_createQfunction.R]
- [ ] [samplesFDistribution.R]

**Comment by choisant** [comment]
Actually not done in folder creation in inferpopulation.

**Comment by pglpm** [comment]
You mean the line `dirname <- paste0(outputdir, suffix)`? this is the string for the folder name, so `file.path` is not needed. Or is it some other line?

**Comment by choisant** [comment]
Ok, we just use file.path() if we are creating a path with separators. That makes sense. We still have to do it in the other files?

**Comment by pglpm** [comment]
> Ok, we just use file.path() if we are creating a path with separators. That makes sense. We still have to do it in the other files?

Must check this! I think I replaced it in all, but have to recheck.
