### ISSUE TITLE
Delay writing of roxygen preliminary comments?

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#23]
@choisant I've noticed that the diff function on new file versions is thrown off by new roxygen comments at the beginning of a file. This makes the diff utility useless and the check of the diffs much more difficult. 

One possible way out: not inserting the initial roxygen comments yet – they can be written or cut-copied into a separate temporary file – and insert them back only when we have converged to a more definitive version of the functions?

**Comment by choisant** [comment]
I don't understand how this can be, please show me next time we meet. Sounds like it's something that can be easily fixed. Worst case we just add the comments without the @ prefixes (are they the problem?), as separating into another document will not work with our brains I think.
