### ISSUE TITLE
Rename 'samplesFdistribution' functions along R conventions?

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#35]
R has the convention of naming `dDISTR` the function that calculates the probability (density) of distribution `DISTR`, and `rDISTR` the function that generates samples from the distribution `DISTR`.

The function `samplesFdistribution()` produces samples of the *frequency distribution* `F(Y|X)` for given `Y` and `X`, so should it be renamed `r[something]`?

Similarly, `inferpopulation()` is generating samples of frequency distributions `F`, from the probability density `P(F|data)`; or, from another point of view, it's generating samples of the parameters that identify such an `F`. So should it be renamed `r[something]` as well?

Similarly for other functions present in the protopackage.

**Comment by choisant** [comment]
I think following conventions is a good idea. As we are adding (good and useful) documentation it is less important that the filenames are intuitive for non-R-developers/your average Dr Joe.

**Comment by pglpm** [comment]
Cool! The problem is finding good names. The very symbol "F" is a bit arbitrary.

**Comment by pglpm** [comment]
Replaced by clearer `Pr()` in commit e029b32fcd40b6675888cb50ddac20a75ffecf10
