### ISSUE TITLE
Avoid use of `data.table`, or block its multi-threading

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#36]
The package `data.table` can start several R threads, which leads to a slow down if this is done in an already-parallelized computation. Two ways out of this:

– Avoid use of `data.table`. Indeed I don't think we really need it (and I find some of its syntax a bit nonsensical)

– Use `setDTthreads(1)` when calling `data.table`.

**Comment by choisant** [comment]
I think the nicest solution is to avoid it, if that is possible.

**Comment by pglpm** [comment]
I'll try to do this next.
