### ISSUE TITLE
Use namespace for all external package

### ISSUE THREAD

**Issue by choisant** [pglpm/bayes_nonparametric_inference#4]
This makes the code easier to read, as it makes it easier to separate what is internal and external functions. It will also trigger more useful error messages if a user does not have the specified package installed.

**Comment by pglpm** [comment]
Note: the following packages do *not* need to be namespaced, because they're base packages:

```
> names(which(installed.packages()[ ,"Priority"] == "base", ))
 [1] "base"      "compiler"  "datasets"  "grDevices" "graphics"  "grid"     
 [7] "methods"   "parallel"  "splines"   "stats"     "stats4"    "tcltk"    
[13] "tools"     "utils"    
```
