### ISSUE TITLE
Avoid use of parallel in samplesFDistribution() and mutualinfo()

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#43]
The parallel computations in `samplesFDistribution` and `mutualinfo` could actually be vectorized. They would be faster, but would also require more RAM.

One possibility is to write a second version of these two functions which use vectorization instead of parallelism; or maybe write it within the functions themselves and provide a user argument for the choice.

**Comment by choisant** [comment]
It would be nice to speed up this function.
I think it makes more sense to make the function vectorized and then just feed in a (1 x nvars) matrix in the case that we want to calculate just one at a time (this is what it does now if I'm not mistaken). The default can be to split the matrix into ncores chunks, but an argument can be to set it either to "1-at-a-time" or a specific nr of rows at a time (this would be a trial and error thing for the advanced user to see if the program runs out of RAM). Non-advanced user would use either default or 1 (corresponding to most memory intensive but fastest and least memory intensive but slowest).

**Comment by pglpm** [comment]
I'm working on this. A further speed-up would be by implementing the main operations in this script as `nimbleFunction`s (basically a C-compiled version). Will work on this.

**Comment by pglpm** [comment]
Update: after some trials, and reviewing also trials and difficulties encountered a year or two ago, the conclusion for now is that vectorization is unfeasible, and the best strategy is to do parallel processing over the required datapoints.

The main problem is RAM consumption: the calculation requires keeping the whole Monte Carlo output, and the required memory would be multiplied by the number of datapoints. This quickly exceeds the available RAM and leads either to crashed or to slow-down for using swap memory.

So for the moment this stays in the back-burner.
