### ISSUE TITLE
'miniter', 'maxiter', 'niterini' confusion

### ISSUE THREAD

**Issue by choisant** [pglpm/bayes_nonparametric_inference#48]
These arguments are hard to document properly because they are not completely logically implemented (in my view). I suggest changing the code/argument names to reflect something that makes more sense to the user.

One solution could be:
miniter - minimum number of MC iterations to try, overriding the diagnostics (but does it make sense for a user to override the diagnostics?)
maxiter - maximum number of MC iterations to try before giving up, regardless of diagnostics.  (I am unsure if this argument should even be available to users now that we have maxhours.)
deltaiter - the maximum step size when increasing nr of MC iterations.

Then the code would have to be changed a little bit to reflect this. Right now in the first iteration of the while loop niterini overrides miniter, but maxiter overrides niterini.

Another option would be to just set miniter to never be smaller than niterini.

**Comment by choisant** [comment]
Those new names and defaults make much more sense to me! The number of iterations are never less than startupMCiterations, which is probably why you gave them the same defaults in the code. I would set it to 0 or equal to startupMCiterations.

I guess users that are not overly familiar with MC sampling should be discouraged from setting those arguments then, and rather stick to the maxHours option.

**Comment by pglpm** [comment]
Cool! easy change, I'll do it now.

> I guess users that are not overly familiar with MC sampling should be discouraged from setting those arguments then, and rather stick to the maxHours option.

This should definitely go in the manual and vignettes indeed!

**Comment by pglpm** [comment]
Done in commit ee456b9e898dbf566353a88e55908f593f4b9b92
