### ISSUE TITLE
Rename "cluster" to "component" in code names and documentation

### ISSUE THREAD

**Issue by pglpm** [pglpm/bayes_nonparametric_inference#49]
The word "cluster" is used in the code and in the documentation to refer to the components of the sum of kernels that represent a frequency distribution. This can be confusing with "cluster" referred to a High Performance Computing context. Better to replace "cluster" in the first sense with "component". For instance `nclusters` → `ncomponents` and so on.

**Comment by choisant** [comment]
I agree, that variable name has confused me.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PierGianLuca ***@***.***>
Sent: Sunday, August 4, 2024 11:48:44 AM
To: pglpm/bayes_nonparametric_inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EKSTERN] [pglpm/bayes_nonparametric_inference] Rename "cluster" to "component" in code names and documentation (Issue #49)


The word "cluster" is used in the code and in the documentation to refer to the components of the sum of kernels that represent a frequency distribution. This can be confusing with "cluster" referred to a High Performance Computing context. Better to replace "cluster" in the first sense with "component". For instance nclusters → ncomponents and so on.
